'use client';

import { useEffect, useRef, useState, type JSX } from 'react';
import { bytesToHex, type Hex } from 'viem';
import { getPayout, randomBytes, type Game } from '@/lib/games';
import GameHud from '@/components/shared/GameHud';
import GameWindow from '@/components/shared/GameWindow';
import MyGameWindow from '@/components/my-game/MyGameWindow';
import MyGameSetupCard from '@/components/my-game/MyGameSetupCard';
import { DEMO_WORDS, myGame } from '@/components/my-game/myGameConfig';
import { BOARD_SIZE, cashOut, createRound, initialState, isRisk, replayFrame, revealPanel, type GameState, type Round } from '@/components/my-game/engine';
import '@/components/my-game/confessional.css';

export default function MyGame({ game: suppliedGame }: { game?: Game }): JSX.Element {
  const game = suppliedGame ?? myGame;
  const [state, setState] = useState<GameState>(initialState);
  // Synchronous state mirror closes the gap before React commits a disabled button.
  const live = useRef(state);
  const timers = useRef<Set<ReturnType<typeof setTimeout>>>(new Set());
  const generation = useRef(0);
  const fixtureIndex = useRef(0);
  const sceneVersion = useRef(0);

  function update(next: GameState): void { live.current = next; setState(next); }
  function clearTimers(): void {
    generation.current++;
    timers.current.forEach(clearTimeout);
    timers.current.clear();
  }
  function later(action: () => void, ms: number): void {
    const token = generation.current;
    const timer = setTimeout(() => {
      timers.current.delete(timer);
      if (generation.current === token) action();
    }, ms);
    timers.current.add(timer);
  }
  useEffect(() => () => {
    generation.current++;
    timers.current.forEach(clearTimeout);
    timers.current.clear();
  }, []);

  function handleReset(): void {
    clearTimers();
    sceneVersion.current++;
    update(initialState());
  }
  async function playGame(gameId?: bigint, randomWord?: Hex): Promise<void> {
    if (live.current.phase !== 'idle') return;
    const { betAmount, mortalSinCount } = live.current;
    if (!isRisk(mortalSinCount) || !Number.isFinite(betAmount) || betAmount < 1 || betAmount > 25) {
      update({ ...live.current, error: 'Choose an Offering between 1 and 25 demo APE.' }); return;
    }
    update({ ...live.current, phase: 'starting', error: null });
    try {
      // Template-generated bytes identify the mock request ONLY, never its outcomes.
      const id = gameId ?? BigInt(bytesToHex(randomBytes(32)));
      const requestWord = randomWord ?? bytesToHex(randomBytes(32));
      const fixture = DEMO_WORDS[fixtureIndex.current++ % DEMO_WORDS.length];
      const factors = Array.from({ length: BOARD_SIZE - mortalSinCount }, (_, i) => getPayout(game.payouts, mortalSinCount, i + 1, 0));
      const round = createRound(id.toString(), fixture, betAmount, mortalSinCount, factors);
      console.log('[CONFESSIONAL DEMO] Mock transaction; no wager or settlement.', { gameId: id.toString(), requestWord });
      later(() => update({ ...live.current, phase: 'playing', currentView: 1, round }), 600);
    } catch (error: unknown) {
      update({ ...live.current, phase: 'idle', currentView: 0, error: error instanceof Error ? error.message : 'The confession could not begin.' });
    }
  }
  function finish(round: Round): void {
    update({ ...live.current, phase: round.outcome === 'sin' ? 'lost' : 'won', currentView: 2,
      round, previousRound: round, pendingPanel: null });
  }
  function handleStateAdvance(panelId: number): void {
    const snapshot = live.current;
    if (snapshot.phase !== 'playing' || !snapshot.round || snapshot.round.selections.some((s) => s.panelId === panelId)) return;
    if (!Number.isInteger(panelId) || panelId < 0 || panelId >= BOARD_SIZE) return;
    update({ ...snapshot, phase: 'revealing', pendingPanel: panelId });
    // Every closed panel has identical timing and appearance until this reveal.
    later(() => {
      const round = revealPanel(snapshot.round!, panelId);
      update({ ...live.current, round, pendingPanel: null });
      later(() => {
        if (round.completed) finish(round);
        else update({ ...live.current, phase: 'playing' });
      }, round.outcome === 'sin' ? 1050 : 430);
    }, 230);
  }
  function handleSeekAbsolution(): void {
    const snapshot = live.current;
    if (snapshot.phase !== 'playing' || !snapshot.round || snapshot.round.safeRevealCount < 1) return;
    const round = cashOut(snapshot.round);
    update({ ...snapshot, phase: 'revealing', round });
    later(() => finish(round), 650);
  }
  async function handlePlayAgain(): Promise<void> {
    if (live.current.currentView !== 2) return;
    const { betAmount, mortalSinCount } = live.current;
    handleReset();
    update({ ...live.current, betAmount, mortalSinCount });
    await playGame();
  }
  function handleRewatch(): void {
    const saved = live.current.previousRound;
    if (live.current.currentView !== 2 || !saved?.completed) return;
    handleReset();
    update({ ...initialState(), phase: 'replaying', currentView: 1, betAmount: saved.wager,
      mortalSinCount: saved.mortalSinCount, round: replayFrame(saved, 0), previousRound: saved });
    const step = (index: number): void => {
      if (index >= saved.selections.length) { later(() => finish(saved), 650); return; }
      update({ ...live.current, pendingPanel: saved.selections[index].panelId });
      later(() => {
        update({ ...live.current, round: replayFrame(saved, index + 1), replayIndex: index + 1, pendingPanel: null });
        later(() => step(index + 1), saved.selections[index].result === 'sin' ? 1050 : index > 5 ? 430 : 570);
      }, 230);
    };
    later(() => step(0), 600);
  }
  function setOffering(value: number): void {
    if (live.current.phase === 'idle') update({ ...live.current, betAmount: value, error: null });
  }
  function setRisk(value: number): void {
    if (live.current.phase === 'idle' && isRisk(value)) update({ ...live.current, mortalSinCount: value });
  }
  const resetWhenAllowed = (): void => {
    if (live.current.currentView === 2 || live.current.phase === 'replaying') handleReset();
  };
  const payout = state.round?.completed ? state.round.wager * state.round.finalPayoutFactor / 10_000 : null;
  return <div className="confessional" data-phase={state.phase}>
    <GameHud key={sceneVersion.current} title={game.title} panel={<MyGameSetupCard state={state} onOffering={setOffering} onRisk={setRisk}
      onPlay={() => void playGame()} onCashout={handleSeekAbsolution} onReset={resetWhenAllowed}
      onRewatch={handleRewatch} onPlayAgain={() => void handlePlayAgain()} />}>
      <GameWindow game={game} hudMode hudSolidBackground disableBuiltInSong isLoading={state.phase === 'starting'}
        isGameFinished={state.currentView === 2} currentGameId={BigInt(state.round?.gameId ?? '0')}
        betAmount={state.betAmount} payout={payout} inReplayMode={state.phase === 'replaying'}
        isUserOriginalPlayer showPNL={false} onReset={resetWhenAllowed}>
        {/* The themed result is rendered in the scene. Omitting onPlayAgain avoids the generic modal. */}
        <MyGameWindow key={sceneVersion.current} state={state} onPanel={handleStateAdvance} onCashout={handleSeekAbsolution}
          onReset={resetWhenAllowed} onRewatch={handleRewatch} />
      </GameWindow>
    </GameHud>
    <details className="cf-rules"><summary>THE RITUAL <span>How to play & demo information</span></summary>
      <div><p>Choose an Offering and 2, 4, 6, or 8 Mortal Sins. Reveal a panel to confess. After one safe Confession, seek absolution to keep the current Blessing. A Mortal Sin ends the round at 0x. Revealing every safe panel grants absolution automatically.</p>
        <p>This is a development demo with predictable fixtures and no real wagers, wallet connection, or payouts. Blessings use fair survival odds, rounded down to the template’s 10,000-unit payout factor. A production house edge and pool limits are not configured.</p>
        <p>Replay Confession repeats the saved round without a new transaction. Reset clears the round. Symbols and shadows are cosmetic and do not change the odds.</p></div>
    </details>
  </div>;
}
